# Generated by Django 6.0.1 on 2026-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='colombia_dot_com_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
