# Generated by Django 6.0.1 on 2026-01-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_theater_colombia_dot_com_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(help_text='Movie title in Spanish', max_length=300)),
                ('original_title', models.CharField(blank=True, default='', help_text='Original language title', max_length=300)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Release year', null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('genre', models.CharField(blank=True, default='', help_text='Primary genre(s)', max_length=100)),
                ('age_rating', models.CharField(blank=True, default='', help_text="Age rating (e.g., 'PG-13', 'R', '+15')", max_length=10)),
                ('synopsis', models.TextField(blank=True, default='', help_text='Movie description/plot summary')),
                ('poster_url', models.URLField(blank=True, default='', help_text='URL to movie poster image', max_length=500)),
                ('imdb_id', models.CharField(blank=True, help_text="IMDB identifier (e.g., 'tt27543632')", max_length=20, null=True, unique=True)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, help_text='The Movie Database (TMDB) identifier', null=True, unique=True)),
                ('tmdb_rating', models.DecimalField(blank=True, decimal_places=1, help_text='TMDB user rating (0.0-10.0)', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'title_es'],
                'indexes': [models.Index(fields=['title_es'], name='movies_app__title_e_a4cbfd_idx'), models.Index(fields=['year'], name='movies_app__year_e10038_idx')],
            },
        ),
    ]
