# Generated by Django 6.0.1 on 2026-01-19 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_add_movie_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('format', models.CharField(blank=True, default='', help_text="Screening format (e.g., '2D', '3D', 'IMAX', 'XD')", max_length=50)),
                ('language', models.CharField(blank=True, default='', help_text="Audio language (e.g., 'DOBLADA', 'SUBTITULADA', 'Original')", max_length=50)),
                ('screen', models.CharField(blank=True, default='', help_text='Screen/sala identifier', max_length=50)),
                ('source_url', models.URLField(blank=True, default='', help_text='URL where this showtime was scraped from', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies_app.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies_app.theater')),
            ],
            options={
                'indexes': [models.Index(fields=['start_date'], name='movies_app__start_d_bef68b_idx'), models.Index(fields=['theater', 'start_date'], name='movies_app__theater_410346_idx'), models.Index(fields=['movie', 'start_date'], name='movies_app__movie_i_1ad9ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('theater', 'movie', 'start_date', 'start_time'), name='unique_showtime')],
            },
        ),
    ]
