# Generated by Django 6.0.1 on 2026-01-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_add_slug_to_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='movies_app__created_8682a4_idx'), models.Index(fields=['task'], name='movies_app__task_a278b8_idx'), models.Index(fields=['severity'], name='movies_app__severit_9a4333_idx')],
            },
        ),
    ]
