# Generated by Django 6.0.1 on 2026-01-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_operationalissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='colombia_dot_com_url',
            field=models.URLField(blank=True, help_text='URL on colombia.com for this movie', max_length=500, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='APICallCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text="Name of the external service (e.g., 'tmdb')", max_length=100)),
                ('date', models.DateField(help_text='Date of the API calls')),
                ('call_count', models.PositiveIntegerField(default=0, help_text='Number of API calls made on this date')),
                ('last_called_at', models.DateTimeField(blank=True, help_text='Timestamp of the last API call on this date', null=True)),
            ],
            options={
                'verbose_name': 'API Call Counter',
                'verbose_name_plural': 'API Call Counters',
                'indexes': [models.Index(fields=['service_name', 'date'], name='movies_app__service_54e86f_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_name', 'date'), name='unique_service_date')],
            },
        ),
    ]
