# Generated by Django 6.0.1 on 2026-01-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_add_colombia_url_and_api_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_url',
            field=models.URLField(blank=True, default='', help_text='URL to movie backdrop image', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_summary',
            field=models.CharField(blank=True, default='', help_text='Top billed actors, comma-separated', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='', help_text='Director name(s)', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, default='', help_text='YouTube trailer URL', max_length=500),
        ),
    ]
