# Generated by Django 6.0.1 on 2026-01-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0008_add_movie_details_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnfindableMovieUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('movie_title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, default='', max_length=500)),
                ('reason', models.CharField(choices=[('no_tmdb_results', 'No TMDB Results'), ('no_match', 'No Match Found'), ('no_metadata', 'Could Not Scrape Metadata'), ('missing_release_date', 'Missing Release Date')], max_length=50)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['url'], name='movies_app__url_792f81_idx'), models.Index(fields=['reason'], name='movies_app__reason_61cd59_idx'), models.Index(fields=['last_seen'], name='movies_app__last_se_a47197_idx')],
            },
        ),
    ]
