# Generated by Django 6.0.1 on 2026-01-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0009_add_unfindable_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unfindablemovieurl',
            name='original_title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
