# Generated by Django 6.0.1 on 2026-01-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0010_alter_unfindable_movie_url_original_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='age_rating',
            new_name='age_rating_colombia',
        ),
    ]
