# Generated by Django 6.0.1 on 2026-01-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0011_rename_age_rating_to_age_rating_colombia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_rating_colombia',
            field=models.CharField(blank=True, default='', help_text="Colombian age rating from TMDB (e.g., '+12', '+15', '+18')", max_length=10),
        ),
    ]
