# Generated by Django 6.0.1 on 2026-01-23 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0012_alter_movie_age_rating_colombia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSourceUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_type', models.CharField(choices=[('colombia_com', 'colombia.com'), ('mamm', 'MAMM (elmamm.org)'), ('cine_colombia', 'Cine Colombia'), ('procinal', 'Procinal'), ('cinemark', 'Cinemark'), ('royal_films', 'Royal Films')], help_text='The scraper/source this URL belongs to', max_length=50)),
                ('url', models.URLField(help_text='URL for this movie on the source website', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_urls', to='movies_app.movie')),
            ],
            options={
                'verbose_name': 'Movie Source URL',
                'verbose_name_plural': 'Movie Source URLs',
                'indexes': [models.Index(fields=['scraper_type', 'url'], name='movies_app__scraper_5a8171_idx')],
                'constraints': [models.UniqueConstraint(fields=('scraper_type', 'url'), name='unique_scraper_url'), models.UniqueConstraint(fields=('movie', 'scraper_type'), name='unique_movie_scraper')],
            },
        ),
    ]
