# Generated by Django 6.0.1 on 2026-01-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0013_moviesourceurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='download_source_url',
            field=models.URLField(blank=True, help_text='URL to scrape for showtimes (may differ from colombia_dot_com_url)', null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='scraper_type',
            field=models.CharField(blank=True, choices=[('colombia_com', 'colombia.com'), ('mamm', 'MAMM (elmamm.org)'), ('cine_colombia', 'Cine Colombia'), ('procinal', 'Procinal'), ('cinemark', 'Cinemark'), ('royal_films', 'Royal Films')], help_text='The scraper to use for downloading showtimes for this theater', max_length=50, null=True),
        ),
    ]
