# Generated by Django 6.0.1 on 2026-01-23 22:46

from django.db import migrations


def backfill_colombia_com_urls(apps, schema_editor):
    """
    Backfill MovieSourceUrl records from existing Movie.colombia_dot_com_url values.
    This ensures movies that were created before the MovieSourceUrl model can still
    be found by URL lookup.
    """
    Movie = apps.get_model("movies_app", "Movie")
    MovieSourceUrl = apps.get_model("movies_app", "MovieSourceUrl")

    movies_with_urls = Movie.objects.exclude(colombia_dot_com_url__isnull=True).exclude(
        colombia_dot_com_url=""
    )

    created_count = 0
    for movie in movies_with_urls:
        _, created = MovieSourceUrl.objects.get_or_create(
            movie=movie,
            scraper_type="COLOMBIA_COM",
            defaults={"url": movie.colombia_dot_com_url},
        )
        if created:
            created_count += 1

    if created_count > 0:
        print(f"Created {created_count} MovieSourceUrl records from existing colombia_dot_com_url values")


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration - remove backfilled records.
    Note: This only removes records that match the colombia_dot_com_url field,
    not records created by subsequent scraper runs.
    """
    Movie = apps.get_model("movies_app", "Movie")
    MovieSourceUrl = apps.get_model("movies_app", "MovieSourceUrl")

    for movie in Movie.objects.exclude(colombia_dot_com_url__isnull=True).exclude(
        colombia_dot_com_url=""
    ):
        MovieSourceUrl.objects.filter(
            movie=movie, scraper_type="COLOMBIA_COM", url=movie.colombia_dot_com_url
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0014_theater_download_source_url_theater_scraper_type'),
    ]

    operations = [
        migrations.RunPython(backfill_colombia_com_urls, reverse_backfill),
    ]
