# Generated by Django 6.0.1 on 2026-01-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0015_backfill_movie_source_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='scraper_config',
            field=models.JSONField(blank=True, help_text='Scraper-specific configuration (e.g., city_id, theater_id for Cineprox)', null=True),
        ),
        migrations.AlterField(
            model_name='moviesourceurl',
            name='scraper_type',
            field=models.CharField(choices=[('colombia_com', 'colombia.com'), ('mamm', 'MAMM (elmamm.org)'), ('cine_colombia', 'Cine Colombia'), ('procinal', 'Procinal'), ('cinemark', 'Cinemark'), ('royal_films', 'Royal Films'), ('cineprox', 'Cineprox')], help_text='The scraper/source this URL belongs to', max_length=50),
        ),
        migrations.AlterField(
            model_name='theater',
            name='scraper_type',
            field=models.CharField(blank=True, choices=[('colombia_com', 'colombia.com'), ('mamm', 'MAMM (elmamm.org)'), ('cine_colombia', 'Cine Colombia'), ('procinal', 'Procinal'), ('cinemark', 'Cinemark'), ('royal_films', 'Royal Films'), ('cineprox', 'Cineprox')], help_text='The scraper to use for downloading showtimes for this theater', max_length=50, null=True),
        ),
    ]
