# Generated by Django 6.0.1 on 2026-01-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0016_add_scraper_config_to_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='language',
        ),
        migrations.AddField(
            model_name='showtime',
            name='translation_type',
            field=models.CharField(blank=True, choices=[('DOBLADO', 'Doblado'), ('SUBTITULADO', 'Subtitulado'), ('ORIGINAL', 'Original')], default='', help_text='Translation type (DOBLADO, SUBTITULADO, ORIGINAL)', max_length=20),
        ),
    ]
