# Generated by Django 6.0.1 on 2026-01-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0017_rename_language_to_translation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='normalized_original_title',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Normalized original_title for fast lookups (lowercase, no accents)', max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='normalized_title',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Normalized title_es for fast lookups (lowercase, no accents)', max_length=300),
        ),
    ]
