# Generated by Django 6.0.1 on 2026-01-27 01:38

import unicodedata

from django.db import migrations


def normalize_title(title: str) -> str:
    """Normalize a title for comparison: lowercase and remove accents."""
    normalized = unicodedata.normalize("NFD", title.lower())
    return "".join(c for c in normalized if unicodedata.category(c) != "Mn").strip()


def populate_normalized_titles(apps, schema_editor):
    """Populate normalized_title and normalized_original_title for existing movies."""
    Movie = apps.get_model("movies_app", "Movie")
    for movie in Movie.objects.all():
        movie.normalized_title = normalize_title(movie.title_es)
        if movie.original_title:
            movie.normalized_original_title = normalize_title(movie.original_title)
        else:
            movie.normalized_original_title = ""
        movie.save(update_fields=["normalized_title", "normalized_original_title"])


def reverse_populate(apps, schema_editor):
    """Clear normalized fields (reverse migration)."""
    Movie = apps.get_model("movies_app", "Movie")
    Movie.objects.all().update(normalized_title="", normalized_original_title="")


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0018_add_normalized_title_fields'),
    ]

    operations = [
        migrations.RunPython(populate_normalized_titles, reverse_populate),
    ]
