# Generated by Django 6.0.1 on 2026-01-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0020_alter_moviesourceurl_scraper_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesourceurl',
            name='scraper_type',
            field=models.CharField(choices=[('colombia_com', 'colombia.com'), ('mamm', 'MAMM (elmamm.org)'), ('cine_colombia', 'Cine Colombia'), ('colombo_americano', 'Colombo Americano'), ('procinal', 'Procinal'), ('cinemark', 'Cinemark'), ('royal_films', 'Royal Films'), ('cineprox', 'Cineprox'), ('cinepolis', 'Cinepolis')], help_text='The scraper/source this URL belongs to', max_length=50),
        ),
        migrations.AlterField(
            model_name='theater',
            name='scraper_type',
            field=models.CharField(blank=True, choices=[('colombia_com', 'colombia.com'), ('mamm', 'MAMM (elmamm.org)'), ('cine_colombia', 'Cine Colombia'), ('colombo_americano', 'Colombo Americano'), ('procinal', 'Procinal'), ('cinemark', 'Cinemark'), ('royal_films', 'Royal Films'), ('cineprox', 'Cineprox'), ('cinepolis', 'Cinepolis')], help_text='The scraper to use for downloading showtimes for this theater', max_length=50, null=True),
        ),
    ]
